### ISSUE TITLE
Feature request for a prebuilt ARM64 OpenSSL 

### ISSUE THREAD

**Issue by ghost** [tutao/better-sqlite3-sqlcipher#1]
Hey all! 

Are you planning on adding a prebuilt ARM64 OpenSSL to better-sqlite3-sqlcipher? 
Are x86_64 OpenSSL and ARM64 OpenSSL able to coexist?
Tutanota desktop would be buildable on ARM64 again. 

kind regards, 
HanoJing

**Comment by ganthern** [comment]
master now has arm64 binaries in the tarball
